### PR TITLE
fix dojo.date.Date namespace hiding global Date, fixes #18

### LINKED ISSUE #18: dojo.date.Date namespace hides global Date in dojo.date typings
The dojo/date functions taking a Date object fail because the dojo.date.Date namespace is used instead of the global Date. Thus, both of these produce an error in TS since it's looking for a dojo.date.Date:

``` typescript
const dt = new Date();
toISOString(dt);
isLeapYear(dt);
```

### PR DESCRIPTION
**Pull request by bitranch**
Also fixed misspelling of "interval" in date.d.ts.

### CODE REVIEW

**Comment by bitranch** [comment]
Do I need to sign yet another CLA (I had 2 on file with Dojo) to get the jQuery Foundation check to quit complaining? There doesn't seem to be any way to see what it thinks it has on file for me.

**Comment by dasa** [comment]
I just had to sign the jQuery CLA for #20

**Comment by dylans** [comment]
At this point, I think we're going to disable the CLA bot as it's just not working... cc @kitsonk

**Comment by kitsonk** [comment]
Sorry, missed this PR... 😢

**Pull request merged**
